Repository analogdotnow/Analog, pull requests merged in 2025-06, with the labels that each got.

#103 Fix token retrieval for fallback active account
  packages/api/src/utils/accounts.ts
Labels: codex

#104 Fix calendars visibility atom file name
  apps/web/src/atoms/calendars-visibility.ts
  apps/web/src/atoms/index.ts
Labels: codex

#117 Fix Temporal.Instant handling for Microsoft calendar
  packages/api/src/providers/microsoft-calendar/utils.ts
Labels: codex, packages

#119 fix(web): upgrade simple analytics to resolve issues
  .env.example
  apps/web/package.json
  bun.lock
  turbo.json
Labels: bug, config

#120 feat(temporal): implement temporal utility functions
  apps/web/package.json
  apps/web/src/components/calendar-view.tsx
  apps/web/src/components/event-calendar/calendar-dnd-context.tsx
  apps/web/src/components/event-calendar/event-dialog.tsx
  apps/web/src/components/event-calendar/event-item.tsx
  apps/web/src/components/event-calendar/events-popup.tsx
  apps/web/src/components/event-calendar/utils/event.ts
  apps/web/src/components/event-calendar/views/day-view.tsx
  apps/web/src/components/event-calendar/views/month-view.tsx
  apps/web/src/components/event-calendar/views/week-view.tsx
  apps/web/src/lib/date-helpers.ts
  apps/web/src/lib/temporal.ts
  bun.lock
  packages/api/package.json
  packages/api/src/providers/microsoft-calendar/utils.ts
  packages/api/src/routers/events.ts
  packages/temporal/eslint.config.mjs
  packages/temporal/package.json
  packages/temporal/src/compare.ts
  packages/temporal/src/convert.ts
  packages/temporal/src/index.ts
  packages/temporal/src/utils.ts
  packages/temporal/tsconfig.json
Labels: UI, packages

#133 chore(web): add discord redirect
  apps/web/next.config.ts
Labels: codex

#149 chore(deps): upgrade packages
  CONTRIBUTING.md
  apps/web/package.json
  apps/web/src/components/sections/home/hero.tsx
  apps/web/src/components/ui/border-trail.tsx
  bun.lock
  package.json
  packages/api/package.json
  packages/auth/package.json
  packages/db/package.json
  packages/env/package.json
  packages/google-calendar/package.json
  packages/google-tasks/package.json
  packages/temporal/package.json
  tooling/eslint-config/package.json
Labels: config, refactor

#152 chore(docs): update google oauth instructions for setting up test users
  CONTRIBUTING.md
  README.md
Labels: documentation, enhancement
