Repository analogdotnow/Analog, pull requests merged in 2025-05, with the labels that each got.

#28 chore(docs): updated README.md with setup instructions
  README.md
Labels: documentation

#16 feat(web): add github link component and theme toggle
  apps/web/src/app/layout.tsx
  apps/web/src/app/page.tsx
  apps/web/src/components/common/github-link.tsx
  apps/web/src/components/common/mode-toggle.tsx
  apps/web/src/components/icons/github.tsx
  bun.lock
Labels: duplicate

#38 bug(web): fix calendar date navigation between sidebar and main view
  apps/web/src/components/calendar-layout.tsx
  apps/web/src/components/date-picker.tsx
  apps/web/src/components/event-calendar/event-calendar.tsx
  apps/web/src/contexts/calendar-context.tsx
  apps/web/src/hooks/use-calendar-state.ts
Labels: enhancement

#51 feat(web): add calendar view preferences
  apps/web/package.json
  apps/web/src/atoms/index.ts
  apps/web/src/atoms/view-preferences.ts
  apps/web/src/components/calendar-view.tsx
  apps/web/src/components/event-calendar/agenda-view.tsx
  apps/web/src/components/event-calendar/calendar-constants.ts
  apps/web/src/components/event-calendar/calendar-content.tsx
  apps/web/src/components/event-calendar/calendar-header.tsx
  apps/web/src/components/event-calendar/calendar-navigation.tsx
  apps/web/src/components/event-calendar/calendar-view-selector.tsx
  apps/web/src/components/event-calendar/calendar-view-title.tsx
  apps/web/src/components/event-calendar/event-calendar.tsx
  apps/web/src/components/event-calendar/hooks/index.ts
  apps/web/src/components/event-calendar/hooks/use-calendar-navigation.ts
  apps/web/src/components/event-calendar/hooks/use-current-time-indicator.ts
  apps/web/src/components/event-calendar/hooks/use-event-dialog.ts
  apps/web/src/components/event-calendar/hooks/use-event-operations.ts
  apps/web/src/components/event-calendar/hooks/use-event-visibility.ts
  apps/web/src/components/event-calendar/hooks/use-keyboard-shortcuts.ts
  apps/web/src/components/event-calendar/hooks/use-view-preferences.ts
  apps/web/src/components/event-calendar/index.ts
  apps/web/src/components/event-calendar/month-view.tsx
  apps/web/src/components/event-calendar/utils.ts
  apps/web/src/components/event-calendar/utils/date-time.ts
  apps/web/src/components/event-calendar/utils/event.ts
  apps/web/src/components/event-calendar/utils/index.ts
  apps/web/src/components/event-calendar/utils/notifications.ts
  apps/web/src/components/event-calendar/utils/ui.ts
  apps/web/src/components/event-calendar/view-preferences-popover.tsx
  apps/web/src/components/event-calendar/week-view.tsx
  apps/web/src/components/footer.tsx
  apps/web/src/components/nav-user.tsx
  apps/web/src/components/ui/label.tsx
  apps/web/src/components/ui/switch.tsx
  apps/web/src/contexts/calendar-context.tsx
  apps/web/src/hooks/use-calendar-state.ts
  bun.lock
Labels: enhancement, help wanted

#75 Layout fixes and alignment with the design
  apps/web/package.json
  apps/web/src/app/calendar/layout.tsx
  apps/web/src/components/app-sidebar.tsx
  apps/web/src/components/date-picker.tsx
  apps/web/src/components/event-calendar/calendar-content.tsx
  apps/web/src/components/event-calendar/calendar-view-selector.tsx
  apps/web/src/components/event-calendar/event-calendar.tsx
  apps/web/src/components/event-calendar/event-item.tsx
  apps/web/src/components/event-calendar/hooks/index.ts
  apps/web/src/components/event-calendar/hooks/use-event-collection.ts
  apps/web/src/components/event-calendar/hooks/use-grid-layout.ts
  apps/web/src/components/event-calendar/index.ts
  apps/web/src/components/event-calendar/month-view.tsx
  apps/web/src/components/event-calendar/utils/date-time.ts
  apps/web/src/components/event-calendar/utils/event.ts
  apps/web/src/components/event-calendar/views/agenda-view.tsx
  apps/web/src/components/event-calendar/views/day-view.tsx
  apps/web/src/components/event-calendar/views/month-view.tsx
  apps/web/src/components/event-calendar/views/week-view.tsx
  apps/web/src/components/ui/calendar.tsx
  apps/web/src/lib/hotkeys/calendar-hotkeys.ts
  apps/web/src/lib/utils.ts
  apps/web/src/styles/date-picker.css
  bun.lock
Labels: bug, help wanted
